services:
  app:
    container_name: catalog_admin_app
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  db:
    container_name: catalog_admin_database
    image: postgres:18.1-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=catalog_admin_database
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data:delegated
    security_opt:
      - seccomp:unconfined
    ports:
      - 5432:5432
